version: "3"

services:
  mysql:
    image: mysql/mysql-server:5.7
    hostname: mysql
    #restart: always
    networks:
      - whmcs
    environment:
      MYSQL_ROOT_PASSWORD: 'secret'
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ROOT_HOST: "%"
    ports:
      - 3306:3306
  whmcs:
    image: fauzie/docker-whmcs:latest
    hostname: whmcs
    networks:
      - whmcs
    #restart: always
    depends_on:
      - mysql
    environment:
      WORKER_PROCESSES: 20
      VIRTUAL_HOST: localhost
      APP_PASSWORD: userapppassword
      WHMCS_SERVER_IP: localhost
      HTTPS: "off"
    ports:
      - 80:80
      - 2222:2222
    volumes:
      - ./whmcs:/var/www/whmcs
  phpmyadmin:
    image: phpmyadmin
    links:
      - mysql
    ports:
      - 8080:80
    environment:
      MYSQL_USERNAME: "root"
      MYSQL_ROOT_PASSWORD: "secret"
      PMA_HOST: mysql
    networks:
      - whmcs
  mailhog:
    image: 'mailhog/mailhog:latest'
    ports:
      - '${FORWARD_MAILHOG_PORT:-1025}:1025'
      - '${FORWARD_MAILHOG_DASHBOARD_PORT:-8025}:8025'
    networks:
      - whmcs
networks:
  whmcs:
    driver: bridge
